import Head from 'next/head'
import BrandColumn from './components/FooterUI/BrandColumn/BrandColumn'
import Footer from './components/FooterUI/Footer/Footer'
import PageLinks from './components/FooterUI/PageLinks/PageLinks'
import GettingStarted from './Sections/GetStarted'
import Stats from './Sections/Stats'
import Features from './Sections/Features'
import Divider from './components/UI/Divider/Divider'
import Hero from './Sections/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Hero />
        <Features />
        <Divider />
        <Stats />
        <GettingStarted />
        <Divider />
      </main>
      <Footer>
        <BrandColumn />
        <PageLinks />
      </Footer>
    </>
  )
}
